### ISSUE TITLE
Official image roadmap

### ISSUE THREAD

**Issue by thibaultcha** [Mashape/docker-kong#4]
https://docs.docker.com/docker-hub/official_repos/
- [x] Git repository
  - [x] Hosted on GitHub
  - [x] Public
- [ ] Dockerfile
  - [x] Written `FROM scratch` or another Official Image.
  - [ ] Follow `Dockerfile` best practises ([1](https://docs.docker.com/articles/dockerfile_best-practices), [2](http://crosbymichael.com/dockerfile-best-practices-take-2.html))
- [ ] Short description
  - [ ] named `README-short.txt`
  - [ ] in the git repo for the `latest` tag
  - [ ] no more than 100 characters
- [ ] Logo
  - [ ] named `logo.png`
  - [ ] in the git repo for the `latest` tag
  - [ ] 200px square, or max-width (preferably square or landscape)
- [ ] Long description
  - [x] named `README.md`
  - [x] in the git repo for the `latest` tag
  - [x] Content
    - [x] Overview & links (What is ...?)
      - [x] Overview of the software
      - [x] Selection of relevant links
      - [x] _mandatory_ link to the Dockerfile 
    - [x] How-to/Usage (How to use...)
      - [x] Describe how to run the image, common use cases and examples. Step-by-step instructions.
        - [x] Link with Cassandra container
        - [x] Custom configuration
        - [x] Example command: `kong reload`
    - [ ] Issues & contributions
      - [ ] Links to contribute to the project
      - [x] Contribution guidelines
      - [ ] A link to [Docker’s resources for contributors](https://docs.docker.com/contributing/contributing/)
      - [ ] Where they can get help
        - [ ] Gitter
        - [ ] Google groups
        - [x] GitHub Issues
- [ ] License
  - [ ] `License` file in the git repo, `latest` tag

**Comment by sinzone** [comment]
+1

**Comment by ahmadnassri** [comment]
have we made any progress on this?

**Comment by thefosk** [comment]
@ahmadnassri I think this needs updates given the recent work that has been done

**Comment by psftw** [comment]
Curious if there are still plans to work towards this, or if we should close the dormant PR on our end: https://github.com/docker-library/official-images/pull/1358

**Comment by thefosk** [comment]
@psftw we definitely want an official Kong image ready, so just give us a few days to update the PR

**Comment by hutchic** [comment]
Now that we have an official kong image can we close this issue?
